server:
  port: 8130 # 服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址

  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tEu94qpLACV1PFnSowj
    keySecret: 5Ye4q7eSB6Ve1dvvN0ncD9nuYOXvUU
    bucketName: srb-file-fjw